1) Bumped CMAKE_ANDROID_API version to 28 to get tests compiling     - fixed undefined reference to aligned_alloc 2) Cleaned up main lib CMakeLists     - got rid of all options for logging/lastErroring on success     - got rid of "feature" options for shit that ain't optional 3) Moved gimbal_test_xx files to "test" subdirectory 4) GblVector     - moved shit out of .h and into .c to stop being a fucking heathen     - cleaned up alloca() macros 5) gimbal_api_frame.h     - cleaned the living shit out of file         * fixed formatting         * removed ancient-ass comments         * removed shit that was no longer used     - got rid of all inlines required for GBL_API_CALL_VERIFY         * turned them into macros         * now you don't have to step through that shit in the debugger     - got rid of unused/ancient-ass util API macros 6) GblType     - stopped forward declaring typedef and moved it into header     - renamed CLASS_CONSTRUCT_IMMEDIATE flag verbose bullshit     - accidentally stuck some DoxyGen comment shit in. Oh well, fixing next commit 7) GblQuark     - stopped forward declaring typedef, moved into header 8) gimbal_test.h     - added signed comparison macros to see if MSVC tests stop shitting 9) GblVectorTestSuite     - added stub, started testing     - shit is fundamentally reested in terms of allocation/storage utilization due to underlying char* compatibilty bullshit 10) GblHashSetTestSuite     - added empty stub header/source for incoming tests 11) GblEnumTestSuite     - cleaned up some ugly-ass string verification shit to use overloaded GBL_TEST_COMPARE() macro
** NO IDEA IF VISUAL STUDIO TESTS WILL BE FIXED YET **